// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0PfjL1yYkKYGK_LkHGFbGA9qrTlRE8I',
    appId: '1:70024593636:web:467137e55862e48b83acf1',
    messagingSenderId: '70024593636',
    projectId: 'intento-2--26-marzo-2025',
    authDomain: 'intento-2--26-marzo-2025.firebaseapp.com',
    storageBucket: 'intento-2--26-marzo-2025.firebasestorage.app',
    measurementId: 'G-RYNXKWM9DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeOLPdXRrCvlyM_1zsaGiPBi4Uz5NVsQ',
    appId: '1:70024593636:android:812a905e341d154e83acf1',
    messagingSenderId: '70024593636',
    projectId: 'intento-2--26-marzo-2025',
    storageBucket: 'intento-2--26-marzo-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtqjyzoh9IJ0iXXwVhckKuPvPitakaSI',
    appId: '1:70024593636:ios:5f0dfac9b496c86783acf1',
    messagingSenderId: '70024593636',
    projectId: 'intento-2--26-marzo-2025',
    storageBucket: 'intento-2--26-marzo-2025.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cRuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtqjyzoh9IJ0iXXwVhckKuPvPitakaSI',
    appId: '1:70024593636:ios:5f0dfac9b496c86783acf1',
    messagingSenderId: '70024593636',
    projectId: 'intento-2--26-marzo-2025',
    storageBucket: 'intento-2--26-marzo-2025.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2cRuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0PfjL1yYkKYGK_LkHGFbGA9qrTlRE8I',
    appId: '1:70024593636:web:1069edc22a55201583acf1',
    messagingSenderId: '70024593636',
    projectId: 'intento-2--26-marzo-2025',
    authDomain: 'intento-2--26-marzo-2025.firebaseapp.com',
    storageBucket: 'intento-2--26-marzo-2025.firebasestorage.app',
    measurementId: 'G-5N0QJ0VMM5',
  );
}
